name: Deploy

on:
  push:
    branches:
      - master

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    # TODO(m-terel): consider to run all ssh commands at once if current execution would be overhead
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        # set rport version to {date-time}-sha:{github-master-head-sha}
        run: go build -v -ldflags="-X 'github.com/cloudradar-monitoring/rport/share.BuildVersion=`date -u +%d-%m-%Y.%H:%M:%S`-sha:`git rev-parse HEAD`'"  -o ./ ./cmd/...

      - name: Copy a new version to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "rportd,rport"
          target: ${{ secrets.DEPLOY_FOLDER }}
          overwrite: true

      - name: Replace bin and Restart rport server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            sudo service rportd stop
            sudo cp /home/github/binaries/{rport,rportd} /usr/local/bin
            sudo service rportd start

  unix-clients:
    name: Unix Clients
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        # set rport version to {date-time}-sha:{github-master-head-sha}
        run: go build -v -ldflags="-X 'github.com/cloudradar-monitoring/rport/share.BuildVersion=`date -u +%d-%m-%Y.%H:%M:%S`-sha:`git rev-parse HEAD`'"  -o ./ ./cmd/rport/...

      - name: Copy a new version to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CLIENTS_HOST }}
          username: ${{ secrets.CLIENTS_USERNAME }}
          port: ${{ secrets.CLIENTS_PORT }}
          key: ${{ secrets.CLIENTS_KEY }}
          source: "rport"
          target: "/home/uploader/rport"

      - name: Restart clients
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLIENTS_HOST }}
          username: ${{ secrets.CLIENTS_USERNAME }}
          port: ${{ secrets.CLIENTS_PORT }}
          key: ${{ secrets.CLIENTS_KEY }}
          script: |
            sudo salt "qa-lin*" state.apply rport.unix.dev-client
            sudo salt "qa-lin*" service.restart rport

  win-clients:
    name: Windows Clients
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        # set rport version to {date-time}-sha:{github-master-head-sha}
        run: GOOS=windows GOARCH=amd64 go build -v -ldflags="-X 'github.com/cloudradar-monitoring/rport/share.BuildVersion=`date -u +%d-%m-%Y.%H:%M:%S`-sha:`git rev-parse HEAD`'"  -o ./ ./cmd/rport/...

      - name: Copy a new version to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CLIENTS_HOST }}
          username: ${{ secrets.CLIENTS_USERNAME }}
          port: ${{ secrets.CLIENTS_PORT }}
          key: ${{ secrets.CLIENTS_KEY }}
          source: "rport.exe"
          target: "/home/uploader/rport"

      - name: Restart clients
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLIENTS_HOST }}
          username: ${{ secrets.CLIENTS_USERNAME }}
          port: ${{ secrets.CLIENTS_PORT }}
          key: ${{ secrets.CLIENTS_KEY }}
          # setting timeout to 60 seconds since default timeout (5s) is not enough
          script: sudo salt -t 60 "test-win*" state.apply rport.win.dev-client
